### ISSUE TITLE
Boot Champ is deprecated as of mac OS El Capitan

### ISSUE THREAD

**Issue by avstjohn** [takeaburgerleaveaburger/googledeyes.com#1]
Alex wants to play Dungeon Siege II, but it can not be blessed!

**Comment by avstjohn** [comment]
Due to SIP (System Integrity Protection) enabled after mac OS 10.10

https://kainjow.tumblr.com/post/128933657269/bootchamp-and-el-capitan

**Comment by deepfriedfilth** [comment]
Just noticing this issue, only 5 months late!
Pretty sure this has been resolved by now, but here's a [guide to disable SIP](https://www.macworld.co.uk/how-to/mac/how-turn-off-mac-os-x-system-integrity-protection-rootless-3638975/) for future reference.
